FROM python:3.10-slim

WORKDIR /bot

RUN apt-get update && apt-get install -y \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Install spesifik CCXT dan Redis untuk algojo
RUN pip install --no-cache-dir ccxt redis python-dotenv requests

# Memasukkan raga bot
COPY bot.py .

# Algojo selalu siaga
CMD ["python", "bot.py"]